create table public.members (
  id bigint generated by default as identity not null,
  name text not null,
  flat_no text not null,
  wing text not null,
  phone text null,
  maintenance_amount numeric null default 0,
  created_at timestamp without time zone null default now(),
  constraint members_pkey primary key (id)
) TABLESPACE pg_default;