create table public.payments (
  id bigint generated by default as identity not null,
  member_id bigint null,
  month integer null,
  year integer null,
  amount numeric null,
  status text null,
  payment_date date null,
  constraint payments_pkey primary key (id),
  constraint payments_member_id_fkey foreign KEY (member_id) references members (id) on delete CASCADE
) TABLESPACE pg_default;